# <center>Блок 5. Математика в ML. Часть I<center>
## <center>Math/ML-1. Линейная алгебра в контексте линейных методов. Часть I<center>
### <center>1.Введение<center>
#### <center>Линейная алгебра в Data Science<center>
#### <center>Основы математического языка: кванторы. Часть I<center>
### <center>2.Основные понятия линейной алгебры: векторы и действия над ними<center>

In [1]:
import numpy as np
import pandas as pd

In [2]:
s = np.array([33, 65, 50, 45])
print(s)
print(s[2])
print(len(s))

[33 65 50 45]
50
4


#### <center>Геометрическая интерпретация вектора. Векторное просранство<center>
#### <center>Базовые операции с векторами<center>

In [3]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a+b)
print(a-b)

[15 23 14  8]
[ 5 -7 -4 -6]


In [4]:
a = np.array([120, 45, 68])
omega = 0.2
c = a*omega
print(c)

[24.   9.  13.6]


In [5]:
# Задание 2.4
x = np.array([5, 2])
y = np.array([-5, -11])
print(x+y)
print(x-y)

[ 0 -9]
[10 13]


In [6]:
# Задание 2.5
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
omega = 72
d = omega*c
e = a+b+d
print(d)
print(e)

[144. 216. 180.]
[394. 496. 500.]


#### <center>Геометрическая интерпретация базовых операций с векторами<center>

#### Линейная комбинация векторов

In [7]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
print(u)

[1800 3000 2700]


#### Скалярное произведение векторов

In [8]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
print(np.dot(a,w))

102.0


#### <center>Векторная запись модели линейной регрессии<center>
### <center>3.Практика: векторы<center>
#### <center>Практика на Python<center>

In [9]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Hut_Paradise_DF

,1.Rent,2.Area,3.Rooms,4.Floor,5.Demo two weeks,6.Liv.Area
0,65,50,3,5,8,37
1,70,52,2,12,4,40
2,120,80,1,10,5,65
3,35,33,1,3,10,20
4,40,33,1,6,20,16
5,50,44,2,13,12,35
6,100,80,4,8,5,60
7,90,65,3,21,1,50
8,85,65,2,5,10,40


In [10]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [11]:
# Задание 3.3
print(Hut_Paradise_values[4])

[40 33  1  6 20 16]


In [12]:
# Задание 3.4
print(Hut_Paradise_values[:,3])

[ 5 12 10  3  6 13  8 21  5]


In [13]:
# Задание 3.5
area = Hut_Paradise_values[:,1]
liv_area = Hut_Paradise_values[:,-1]
no_liv_area = area - liv_area
print(no_liv_area)

[13 12 15 13 17  9 20 15 25]


In [14]:
# Задание 3.6
demo = Hut_Paradise_values[:,4]
minutes = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
all_demo = np.dot(demo,minutes)
print(all_demo)

1348


In [15]:
# Задание 3.7
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

a = 2*v + (-3*w)
print(a)

[-3 14  3  4  2]


In [16]:
# Задание 3.8
b = np.dot(u,a)
b

0

### <center>4.Основные понятия линейной алгебры: матрицы и базовые действия с ними<center>

In [17]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [18]:
print(A.shape)

print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

(4, 3)
a_23= 1 a_32= 3 a_33= 1


#### <center>Классификация матриц по форме и содержанию<center>
#### <center>Базовые действия над матрицами<center>
#### <center>Применение базовых операций для обработки изображений<center>
### <center>5.Практика: базовые действия над матрицами<center>

In [19]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [20]:
# Задание 5.1
inc_data = pd.DataFrame([Husband_Income, Wife_Income, Mother_In_Law_Income])
inc_matrix = inc_data.values
inc_matrix = inc_matrix.T
inc_matrix

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [21]:
# Задание 5.2
cons_data = pd.DataFrame([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
cons_matrix = cons_data.values
cons_matrix = cons_matrix.T
cons_matrix

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [22]:
# Задание 5.3
bill = 0.13*inc_matrix
after_bill = inc_matrix - bill
after_bill[0]

array([ 87. , 130.5,  78.3])

In [23]:
# Задание 5.4
P = after_bill - cons_matrix
P[2]

array([ 61.8, -26.9, -53. ])

### <center>6.Матричное умножение<center>
#### <center>Произведение двух матриц<center>

In [24]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")
print(np.dot(A,B))
print()
print(np.dot(B,A))

[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]

[[  5 -13]
 [ -1  11]]


#### <center>Произведение матриц и вектора<center>
#### <center>Геометрическая интерпретация умножения матрицы на вектор<center>
#### <center>Умножение на специальные матрицы<center>
#### <center>Умножение и транспонирование матриц<center>
#### <center>Матрица Грама<center>
### <center>7.Практика: матричное умножение<center>

In [25]:
# Задание 7.1
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(np.dot(A,x))

[26 30]


In [26]:
# Задание 7.2

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
np.dot(B,A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [27]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x,y,z])

G = np.dot(A.T, A)
print(G)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [28]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Count_matrix = Count_DF.values
Price_matrix = Price_DF.values
print(Count_matrix.shape)
print(Price_matrix.shape)

(8, 5)
(8, 5)


In [29]:
# Задание 7.4

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

salon_inc = Price_matrix*Count_matrix
np.dot(salon_inc, com)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [30]:
# Задание 7.5

ones = np.ones(5)
income = ones-com
np.dot(salon_inc, income)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

### <center>8.Обратная матрица. Определитель матрицы<center>

In [31]:
A = np.matrix('1,2,3; 4,5,6; 7,8,10')
A

np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

#### <center>Определитель матрицы<center>

In [32]:
A = np.matrix("1, 2, 3; 4, 5, 6; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


In [33]:
# Задание 8.8

A = np.matrix("2, 0, 0; 0, 1, 0; 0, 0, 4")
B = np.linalg.inv(A)
print(round(np.linalg.det(A)))
print(round(np.linalg.det(B),3))

8
0.125


### <center>9.СЛАУ. Линейная зависимость векторов. Ранг матрицы. Базис<center>
#### <center>Системы линейных алгебраических уравнений<center>
#### <center>Матричная запись СЛАУ<center>
#### <center>Линейная зависимость системы векторов<center>
#### <center>Ранг матрицы. Базис<center>

In [34]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


In [35]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


### <center>10.Практика: обратная матрица, определитель, ранг<center>

In [ ]:
# Задание 10.1

A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
A1 = np.linalg.inv(A)
print(round(A1[1][0],3))

0.375


In [41]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [ ]:
# Задание 10.2

A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))

4


In [ ]:
# Задание 10.4

G = A.T@A
print(G[0][3])

-35


In [46]:
# Задание 10.5

print(round(np.linalg.det(G)))

3716648


In [49]:
# Задание 10.7

G1 = np.linalg.inv(G)
print(round(G1[2][0],3))

-0.026
