# <center>Блок 5. Математика в ML. Часть I<center>
## <center>Math/ML-1. Линейная алгебра в контексте линейных методов. Часть I<center>
### <center>1.Введение<center>
#### <center>Линейная алгебра в Data Science<center>
#### <center>Основы математического языка: кванторы. Часть I<center>
### <center>2.Основные понятия линейной алгебры: векторы и действия над ними<center>

In [1]:
import numpy as np

s = np.array([33, 65, 50, 45])
print(s)
print(s[2])
print(len(s))

[33 65 50 45]
50
4


#### <center>Геометрическая интерпретация вектора. Векторное просранство<center>
#### <center>Базовые операции с векторами<center>

In [2]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a+b)
print(a-b)

[15 23 14  8]
[ 5 -7 -4 -6]


In [3]:
a = np.array([120, 45, 68])
omega = 0.2
c = a*omega
print(c)

[24.   9.  13.6]


In [4]:
# Задание 2.4
x = np.array([5, 2])
y = np.array([-5, -11])
print(x+y)
print(x-y)

[ 0 -9]
[10 13]


In [5]:
# Задание 2.5
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
omega = 72
d = omega*c
e = a+b+d
print(d)
print(e)

[144. 216. 180.]
[394. 496. 500.]


#### <center>Геометрическая интерпретация базовых операций с векторами<center>

#### Линейная комбинация векторов

In [6]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
print(u)

[1800 3000 2700]
